###########################################################
# GCC template makefile
###########################################################

FREERTOS_HEAP_SOURCES = 
FREERTOS_HEAP_SOURCES += heap_1.c

C_SOURCES += $(FREERTOS_HEAP_SOURCES)