###########################################################
# GCC template makefile
###########################################################


ESP8266_12E_SOURCES = 
ESP8266_12E_SOURCES += 

EXTRAINCDIRS += $(TOP)/moduleTestCode/ESP8266_12E/Inc