###########################################################
# GCC template makefile
###########################################################

FREERTOS_PORT_SOURCES = 
FREERTOS_PORT_SOURCES += port.c


C_SOURCES += $(FREERTOS_PORT_SOURCES)