###########################################################
# GCC template makefile
###########################################################


LED_ON_OFF_ALL_SOURCE = 
LED_ON_OFF_ALL_SOURCE += main.c

EXTRAINCDIRS += $(TOP)/SampleChapter/StudyCode/MStory2.0/MANGO-M3/04.M32.Src005.LedAllOnOff/Inc

C_SOURCES += $(LED_ON_OFF_ALL_SOURCE)