###########################################################
# GCC template makefile
###########################################################

LED_ON_OFF_SOURCES = main.c


EXTRAINCDIRS += $(TOP)/SampleChapter/StudyCode/MStory2.0/MANGO-M3/01.M32.Src001.LedOn/Inc
C_SOURCES += $(LED_ON_OFF_SOURCES)