###########################################################
# GCC template makefile
###########################################################

LED_OFF_SOURCES = 
LED_OFF_SOURCES += main.c


EXTRAINCDIRS += $(TOP)/SampleChapter/StudyCode/MStory2.0/MANGO-M3/03.M32.Src003.LedOff/Inc
C_SOURCES += $(LED_OFF_SOURCES)