###########################################################
# GCC template makefile
###########################################################

TIM_INTERRUPT_TEST_SOURCES = 
TIM_INTERRUPT_TEST_SOURCES += 
TIM_INTERRUPT_TEST_SOURCES += 


EXTRAINCDIRS += $(TOP)/StudyProject/Edu_Board/06.TIM-Interrupt_Test/Inc

C_SOURCES += $(TIM_INTERRUPT_TEST_SOURCES)