###########################################################
# GCC template makefile
###########################################################

LED_ON_OFF_SOURCES = main.c


EXTRAINCDIRS += $(TOP)/SampleChapter/StudyCode/MStory2.0/MANGO-M3/02.M32.Src001.LedOn.2009.1022.1419/Inc
C_SOURCES += $(LED_ON_OFF_SOURCES)